# -*- coding: utf-8 -*-
"""Day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ZP6NpoztPpefCfx8O9s0b0blK5We7Oh
"""

print("HELLO,World!")
print("Mohammed Twahir")
print("CSE")

def is_prime(n):
    if n <= 1:
        return False
    if n == 2:
        return True  # 2 is the only even prime number
    if n % 2 == 0:
        return False
    # Check odd numbers up to the square root of n
    for i in range(3, int(n**0.5) + 1, 2):
        if n % i == 0:
            return False
    return True

# Example usage
num = 29
print(f"{num} is prime: {is_prime(num)}")

a=10
b=3.14
name= 'rajesh'
print(a,b,name)
print(name + 'good')

"""# ***user input* **

"""

name = input('Enter student name: ')
a= int(input('enter a number: '))
print(name)
print(a)

"""# ADD TWO NUMBERS

"""

a=10
b=122
c=a+b
print(c)

"""# **                                       OR**"""

a=int(input('enter a number: '))
b=int(input('enter a number: '))
c=(a+b)
print(c)

"""## **Multiplication**"""

a=int(input('enter a number: '))
b=int(input('enter a number: '))
c=(a*b)
print(c)

"""## ***AREA OF CIRCLE***"""

radius = float(input("Enter the radius of the circle: "))
pi = 3.14159
area = pi* radius**2
print("The area of the circle is:", area)

"""# ****DIVISION***"""

a=int(input('enter a number: '))
b=int(input('enter a number: '))
print(a/b)